server:
  port: 7001    # 端口设置    
  
eureka:
  instance:
    hostname: eureka7001.com    # eureka 服务端的实例名称,单机版为localhost，eureka7001
  client:
    register-with-eureka: false   # 不向注册中心注册自己
    fetch-registry: false   # 不需要去检索服务，自己就是服务中心，职责是维护服务
    service-url:   
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与Eureka Server交互的地址查询查询和服务注册都需要依赖这个地址    
     defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 